CODE = "code"
FIND_DEVICE_TIMESTAMP_DELTA = 5 * 60 * 1000
GET_FRIEND_MAP_POSITION_TIMESTAMP_DELTA = 5 * 60 * 1000
GET_MAP_POSITION_TIMESTAMP_DELTA = 10 * 60 * 1000

LESS_THAN_TWO_SECOND_SAMPLE = 5 * 1000   # 在最近两秒内采样
LESS_THAN_ONE_SECOND_SAMPLE = 3 * 1000   # 在最近两秒内采样

REDIS_DUPLEX_AGREE_PREFIX = "user_id_"

# ALIYUN_DAYU_ACCESS_KEY_ID = "LTAIcWv2dgaOCkng"
# ALIYUN_DAYU_ACCESS_KEY_SECRET = "i13SMvTzNwhyAwvz0JM6NvkkXTbPKq"
# 推送的类型：1，申请见面；2，同意见面；3.取消见面；4.拒绝见面；
#        5.申请好友；6. 同意好友；7.拒绝好友；8.删除好友

PUSH_STATE_TYPE_APPLY_MEET = 1
PUSH_STATE_TYPE_AGREE_MEET = 2
PUSH_STATE_TYPE_MEETING = 3
PUSH_STATE_TYPE_CANCEL_MEET = 4
PUSH_STATE_TYPE_REFUSE_MEET = 5
PUSH_STATE_TYPE_END_MEET = 6
PUSH_STATE_TYPE_MET = 7
PUSH_STATE_TYPE_SINGLE_AGREE_MEET = 8
PUSH_STATE_TYPE_SINGLE_MEET = 9

PUSH_STATE_TYPE_APPLY_FRIEND = 11
PUSH_STATE_TYPE_AGREE_FRIEND = 12
PUSH_STATE_TYPE_REFUSE_FRIEND = 13
PUSH_STATE_TYPE_REMOVE_FRIEND = 14

REDIS_MAP_INFORMATION = "map_information"
REDIS_GEO_POSITION = "geo_position"
