SELECT "########################################" AS start;
SELECT now() AS now;
USE ohho;
SELECT "****************************delete match" AS description;
DELETE FROM ohho_record_match_apply;
DELETE FROM ohho_record_match_agree;
DELETE FROM ohho_record_match_refuse;
DELETE FROM ohho_record_exclude;
DELETE FROM ohho_record_match_duplex_agree;
SELECT "*****************************delete meet" AS description;
DELETE FROM ohho_record_match_meeting;
DELETE FROM ohho_record_match_meet;
DELETE FROM ohho_record_match_meet_end;
DELETE FROM ohho_record_match_met;
SELECT "***************************delete friend" AS description;
DELETE FROM ohho_record_friend_apply;
DELETE FROM ohho_record_friend_agree;
DELETE FROM ohho_record_friend_refuse;
SELECT "************************delete friend im" AS description;
DELETE FROM ohho_im_user_relation;
SELECT "########################################" AS end;