"""empty message

Revision ID: 051cd5f6204c
Revises: e456eb6c0e3a
Create Date: 2017-12-21 17:35:15.992750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051cd5f6204c'
down_revision = 'e456eb6c0e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
