"""empty message

Revision ID: 0f1056ebcdb6
Revises: b300f479cf1e
Create Date: 2017-12-21 13:19:39.743381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1056ebcdb6'
down_revision = 'b300f479cf1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_interest', sa.Column('key', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohho_interest', 'key')
    # ### end Alembic commands ###
