"""empty message

Revision ID: 25da46b29adf
Revises: 66f4ee93815a
Create Date: 2017-12-21 17:40:55.855783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25da46b29adf'
down_revision = '66f4ee93815a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
