"""empty message

Revision ID: 2c3bf3a03fdb
Revises: 5ac67a4bfe2d
Create Date: 2017-12-04 15:31:03.910521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3bf3a03fdb'
down_revision = '5ac67a4bfe2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
