"""empty message

Revision ID: 38db863d8a67
Revises: 25da46b29adf
Create Date: 2017-12-22 14:55:48.895224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38db863d8a67'
down_revision = '25da46b29adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
