"""empty message

Revision ID: 422429f44740
Revises: ad666d46e60e
Create Date: 2017-11-17 14:51:52.069502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '422429f44740'
down_revision = 'ad666d46e60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_map_information', sa.Column('geohash_code', sa.String(length=20), nullable=True))
    op.add_column('ohho_user', sa.Column('country_code_id', sa.Integer(), nullable=True))
    op.drop_constraint('ohho_user_ibfk_1', 'ohho_user', type_='foreignkey')
    op.create_foreign_key(None, 'ohho_user', 'ohho_country_code', ['country_code_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ohho_user', 'country_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_user', sa.Column('country_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ohho_user', type_='foreignkey')
    op.create_foreign_key('ohho_user_ibfk_1', 'ohho_user', 'ohho_country_code', ['country_code'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ohho_user', 'country_code_id')
    op.drop_column('ohho_map_information', 'geohash_code')
    # ### end Alembic commands ###
