"""empty message

Revision ID: 4c7894f5bac1
Revises: cd9a3da6dab2
Create Date: 2017-12-04 15:09:19.755781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7894f5bac1'
down_revision = 'cd9a3da6dab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
