"""empty message

Revision ID: 4d977d394190
Revises: 5e3b610c9fc7
Create Date: 2017-11-28 11:17:30.780421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d977d394190'
down_revision = '5e3b610c9fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_phone_position', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('test_phone_position', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('test_phone_position', sa.Column('angle', sa.Float(), nullable=True))
    op.add_column('test_phone_position', sa.Column('aoi', sa.String(length=64), nullable=True))
    op.add_column('test_phone_position', sa.Column('area', sa.String(length=32), nullable=True))
    op.add_column('test_phone_position', sa.Column('area_code', sa.String(length=32), nullable=True))
    op.add_column('test_phone_position', sa.Column('building_id', sa.Integer(), nullable=True))
    op.add_column('test_phone_position', sa.Column('city', sa.String(length=32), nullable=True))
    op.add_column('test_phone_position', sa.Column('city_code', sa.String(length=32), nullable=True))
    op.add_column('test_phone_position', sa.Column('country', sa.String(length=32), nullable=True))
    op.add_column('test_phone_position', sa.Column('floor', sa.String(length=16), nullable=True))
    op.add_column('test_phone_position', sa.Column('interest_point', sa.String(length=64), nullable=True))
    op.add_column('test_phone_position', sa.Column('position_time', sa.DateTime(), nullable=True))
    op.add_column('test_phone_position', sa.Column('province', sa.String(length=32), nullable=True))
    op.add_column('test_phone_position', sa.Column('satellite_number', sa.Integer(), nullable=True))
    op.add_column('test_phone_position', sa.Column('speed', sa.String(length=16), nullable=True))
    op.add_column('test_phone_position', sa.Column('supplier', sa.String(length=32), nullable=True))
    op.add_column('test_phone_position', sa.Column('type', sa.Integer(), nullable=True))
    op.add_column('test_rssi', sa.Column('device', sa.String(length=64), nullable=True))
    op.add_column('test_rssi', sa.Column('phone', sa.String(length=64), nullable=True))
    op.add_column('test_rssi', sa.Column('rssi', sa.Integer(), nullable=True))
    op.add_column('test_rssi', sa.Column('type', sa.SmallInteger(), nullable=True))
    op.drop_column('test_rssi', 'self_rssi')
    op.drop_column('test_rssi', 'user')
    op.drop_column('test_rssi', 'other_rssi')
    op.add_column('test_rssi_distance', sa.Column('phone', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_rssi_distance', 'phone')
    op.add_column('test_rssi', sa.Column('other_rssi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('test_rssi', sa.Column('user', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('test_rssi', sa.Column('self_rssi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('test_rssi', 'type')
    op.drop_column('test_rssi', 'rssi')
    op.drop_column('test_rssi', 'phone')
    op.drop_column('test_rssi', 'device')
    op.drop_column('test_phone_position', 'type')
    op.drop_column('test_phone_position', 'supplier')
    op.drop_column('test_phone_position', 'speed')
    op.drop_column('test_phone_position', 'satellite_number')
    op.drop_column('test_phone_position', 'province')
    op.drop_column('test_phone_position', 'position_time')
    op.drop_column('test_phone_position', 'interest_point')
    op.drop_column('test_phone_position', 'floor')
    op.drop_column('test_phone_position', 'country')
    op.drop_column('test_phone_position', 'city_code')
    op.drop_column('test_phone_position', 'city')
    op.drop_column('test_phone_position', 'building_id')
    op.drop_column('test_phone_position', 'area_code')
    op.drop_column('test_phone_position', 'area')
    op.drop_column('test_phone_position', 'aoi')
    op.drop_column('test_phone_position', 'angle')
    op.drop_column('test_phone_position', 'altitude')
    op.drop_column('test_phone_position', 'address')
    # ### end Alembic commands ###
