"""empty message

Revision ID: 509e44fb5472
Revises: 38db863d8a67
Create Date: 2017-12-22 15:51:59.947836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509e44fb5472'
down_revision = '38db863d8a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
