"""empty message

Revision ID: 53e4216db1b9
Revises: ae15f2fb5567
Create Date: 2017-11-14 09:37:17.496932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53e4216db1b9'
down_revision = 'ae15f2fb5567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ohho_record_match_meet_state')
    op.drop_constraint('ohho_feedback_ibfk_1', 'ohho_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'ohho_feedback', 'ohho_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('ohho_interest_ibfk_1', 'ohho_interest', type_='foreignkey')
    op.create_foreign_key(None, 'ohho_interest', 'ohho_interest', ['parent_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('ohho_match_condition', sa.Column('interest', sa.String(length=128), nullable=True))
    op.drop_constraint('ohho_record_exclude_ibfk_3', 'ohho_record_exclude', type_='foreignkey')
    op.drop_column('ohho_record_exclude', 'match_condition_id')
    op.add_column('ohho_record_match_meet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ohho_record_match_meet', 'ohho_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('ohho_record_match_meet_end', sa.Column('address', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'ohho_record_user_and_match_condition', ['match_condition_id'])
    op.add_column('ohho_user_accuracy_extension', sa.Column('exclude', sa.String(length=1024), nullable=True))
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_3', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_4', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_5', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_7', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_6', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_column('ohho_user_accuracy_extension', 'smoke_id')
    op.drop_column('ohho_user_accuracy_extension', 'industry_id')
    op.drop_column('ohho_user_accuracy_extension', 'work_domain_id')
    op.drop_column('ohho_user_accuracy_extension', 'drink_id')
    op.drop_column('ohho_user_accuracy_extension', 'profession_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_user_accuracy_extension', sa.Column('profession_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('drink_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('work_domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('industry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('smoke_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_6', 'ohho_user_accuracy_extension', 'ohho_industry', ['industry_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_7', 'ohho_user_accuracy_extension', 'ohho_profession', ['profession_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_5', 'ohho_user_accuracy_extension', 'ohho_smoke', ['smoke_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_4', 'ohho_user_accuracy_extension', 'ohho_drink', ['drink_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_3', 'ohho_user_accuracy_extension', 'ohho_work_domain', ['work_domain_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ohho_user_accuracy_extension', 'exclude')
    op.drop_constraint(None, 'ohho_record_user_and_match_condition', type_='unique')
    op.drop_column('ohho_record_match_meet_end', 'address')
    op.drop_constraint(None, 'ohho_record_match_meet', type_='foreignkey')
    op.drop_column('ohho_record_match_meet', 'user_id')
    op.add_column('ohho_record_exclude', sa.Column('match_condition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('ohho_record_exclude_ibfk_3', 'ohho_record_exclude', 'ohho_record_match_condition', ['match_condition_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ohho_match_condition', 'interest')
    op.drop_constraint(None, 'ohho_interest', type_='foreignkey')
    op.create_foreign_key('ohho_interest_ibfk_1', 'ohho_interest', 'ohho_interest', ['parent_id'], ['id'])
    op.drop_constraint(None, 'ohho_feedback', type_='foreignkey')
    op.create_foreign_key('ohho_feedback_ibfk_1', 'ohho_feedback', 'ohho_device', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_table('ohho_record_match_meet_state',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('changed_at', mysql.DATETIME(), nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('apply_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['apply_id'], ['ohho_record_match_apply.id'], name='ohho_record_match_meet_state_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ohho_user.id'], name='ohho_record_match_meet_state_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
