"""empty message

Revision ID: 5ac67a4bfe2d
Revises: 4c7894f5bac1
Create Date: 2017-12-04 15:30:53.988045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac67a4bfe2d'
down_revision = '4c7894f5bac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
