"""empty message

Revision ID: 5e3b610c9fc7
Revises: b86534dfc6b4
Create Date: 2017-11-28 09:38:49.037042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3b610c9fc7'
down_revision = 'b86534dfc6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
