"""empty message

Revision ID: 66f4ee93815a
Revises: 051cd5f6204c
Create Date: 2017-12-21 17:38:43.423727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f4ee93815a'
down_revision = '051cd5f6204c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
