"""empty message

Revision ID: 68c1f7c60646
Revises: 9483d3cb1828
Create Date: 2017-10-24 09:48:15.117037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c1f7c60646'
down_revision = '9483d3cb1828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
