"""empty message

Revision ID: 73bc6cbf6787
Revises: aa06c4e022a6
Create Date: 2017-11-22 15:12:15.808362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bc6cbf6787'
down_revision = 'aa06c4e022a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
