"""empty message

Revision ID: 7480f5424cd6
Revises: 2c3bf3a03fdb
Create Date: 2017-12-05 12:08:15.108915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7480f5424cd6'
down_revision = '2c3bf3a03fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_user_description', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    op.add_column('ohho_user_favourite_book', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    op.add_column('ohho_user_favourite_movie', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    op.add_column('ohho_user_favourite_music', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    op.add_column('ohho_user_favourite_sport', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    op.add_column('ohho_user_icon', sa.Column('is_head_sculpture', sa.SmallInteger(), nullable=True))
    op.add_column('ohho_user_icon', sa.Column('thumbnail', sa.String(length=128), nullable=True))
    op.add_column('ohho_user_icon', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    op.add_column('ohho_user_impression', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohho_user_impression', 'timestamp')
    op.drop_column('ohho_user_icon', 'timestamp')
    op.drop_column('ohho_user_icon', 'thumbnail')
    op.drop_column('ohho_user_icon', 'is_head_sculpture')
    op.drop_column('ohho_user_favourite_sport', 'timestamp')
    op.drop_column('ohho_user_favourite_music', 'timestamp')
    op.drop_column('ohho_user_favourite_movie', 'timestamp')
    op.drop_column('ohho_user_favourite_book', 'timestamp')
    op.drop_column('ohho_user_description', 'timestamp')
    # ### end Alembic commands ###
