"""empty message

Revision ID: 80a812bab51a
Revises: 73bc6cbf6787
Create Date: 2017-11-22 15:14:26.221322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a812bab51a'
down_revision = '73bc6cbf6787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
