"""empty message

Revision ID: 9483d3cb1828
Revises: aba206893d91
Create Date: 2017-10-24 09:31:59.820202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9483d3cb1828'
down_revision = 'aba206893d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_record_match_apply', sa.Column('message', sa.String(length=256), nullable=True))
    op.add_column('ohho_record_match_meet_end', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ohho_record_match_meet_end', 'ohho_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('ohho_record_match_refuse', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('ohho_record_match_refuse', sa.Column('information', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohho_record_match_refuse', 'information')
    op.drop_column('ohho_record_match_refuse', 'distance')
    op.drop_constraint(None, 'ohho_record_match_meet_end', type_='foreignkey')
    op.drop_column('ohho_record_match_meet_end', 'user_id')
    op.drop_column('ohho_record_match_apply', 'message')
    # ### end Alembic commands ###
