"""empty message

Revision ID: a1cb821c2383
Revises: 422429f44740
Create Date: 2017-11-21 17:35:26.206363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1cb821c2383'
down_revision = '422429f44740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_2', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_column('ohho_user_accuracy_extension', 'body_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_user_accuracy_extension', sa.Column('body_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_2', 'ohho_user_accuracy_extension', 'ohho_body_type', ['body_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
