"""empty message

Revision ID: aa06c4e022a6
Revises: a1cb821c2383
Create Date: 2017-11-22 15:07:14.617582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa06c4e022a6'
down_revision = 'a1cb821c2383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_permission_group', sa.Column('description', sa.String(length=1024), nullable=True))
    op.drop_column('ohho_permission_group', 'permission')
    op.drop_index('index', table_name='ohho_permission_page')
    op.drop_column('ohho_permission_page', 'index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_permission_page', sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('index', 'ohho_permission_page', ['index'], unique=True)
    op.add_column('ohho_permission_group', sa.Column('permission', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('ohho_permission_group', 'description')
    # ### end Alembic commands ###
