"""empty message

Revision ID: aba206893d91
Revises: 7341c8a3fa89
Create Date: 2017-10-23 11:40:07.149814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba206893d91'
down_revision = '7341c8a3fa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_6', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_3', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_2', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_4', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_5', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint('ohho_user_accuracy_extension_ibfk_7', 'ohho_user_accuracy_extension', type_='foreignkey')
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_body_type', ['body_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_work_domain', ['work_domain_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_drink', ['drink_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_smoke', ['smoke_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_industry', ['industry_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_profession', ['profession_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_7', 'ohho_user_accuracy_extension', 'ohho_profession', ['profession_id'], ['id'])
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_5', 'ohho_user_accuracy_extension', 'ohho_drink', ['drink_id'], ['id'])
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_4', 'ohho_user_accuracy_extension', 'ohho_smoke', ['smoke_id'], ['id'])
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_2', 'ohho_user_accuracy_extension', 'ohho_industry', ['industry_id'], ['id'])
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_3', 'ohho_user_accuracy_extension', 'ohho_body_type', ['body_type_id'], ['id'])
    op.create_foreign_key('ohho_user_accuracy_extension_ibfk_6', 'ohho_user_accuracy_extension', 'ohho_work_domain', ['work_domain_id'], ['id'])
    # ### end Alembic commands ###
