"""empty message

Revision ID: ac4cf40c46fc
Revises: 80a812bab51a
Create Date: 2017-11-24 10:12:35.993282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4cf40c46fc'
down_revision = '80a812bab51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_record_match_agree', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('ohho_record_match_agree', sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_agree', sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_duplex_agree', sa.Column('another_user_address', sa.String(length=128), nullable=True))
    op.add_column('ohho_record_match_duplex_agree', sa.Column('another_user_latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_duplex_agree', sa.Column('another_user_longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_duplex_agree', sa.Column('user_address', sa.String(length=128), nullable=True))
    op.add_column('ohho_record_match_duplex_agree', sa.Column('user_latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_duplex_agree', sa.Column('user_longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_meet', sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_meet', sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_met', sa.Column('another_user_latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_met', sa.Column('another_user_longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_met', sa.Column('user_latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ohho_record_match_met', sa.Column('user_longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohho_record_match_met', 'user_longitude')
    op.drop_column('ohho_record_match_met', 'user_latitude')
    op.drop_column('ohho_record_match_met', 'another_user_longitude')
    op.drop_column('ohho_record_match_met', 'another_user_latitude')
    op.drop_column('ohho_record_match_meet', 'longitude')
    op.drop_column('ohho_record_match_meet', 'latitude')
    op.drop_column('ohho_record_match_duplex_agree', 'user_longitude')
    op.drop_column('ohho_record_match_duplex_agree', 'user_latitude')
    op.drop_column('ohho_record_match_duplex_agree', 'user_address')
    op.drop_column('ohho_record_match_duplex_agree', 'another_user_longitude')
    op.drop_column('ohho_record_match_duplex_agree', 'another_user_latitude')
    op.drop_column('ohho_record_match_duplex_agree', 'another_user_address')
    op.drop_column('ohho_record_match_agree', 'longitude')
    op.drop_column('ohho_record_match_agree', 'latitude')
    op.drop_column('ohho_record_match_agree', 'address')
    # ### end Alembic commands ###
