"""empty message

Revision ID: ad666d46e60e
Revises: 53e4216db1b9
Create Date: 2017-11-17 09:44:36.789178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad666d46e60e'
down_revision = '53e4216db1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_user', sa.Column('cellphone', sa.String(length=20), nullable=True))
    op.add_column('ohho_user', sa.Column('country_code', sa.Integer(), nullable=True))
    op.add_column('ohho_user', sa.Column('last_cellphone', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'ohho_user', 'ohho_country_code', ['country_code'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ohho_user', type_='foreignkey')
    op.drop_column('ohho_user', 'last_cellphone')
    op.drop_column('ohho_user', 'country_code')
    op.drop_column('ohho_user', 'cellphone')
    # ### end Alembic commands ###
