"""empty message

Revision ID: ae15f2fb5567
Revises: 68c1f7c60646
Create Date: 2017-10-24 09:57:24.207295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae15f2fb5567'
down_revision = '68c1f7c60646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_record_friend_apply', sa.Column('message', sa.String(length=256), nullable=True))
    op.add_column('ohho_record_match_agree', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ohho_record_match_agree', 'ohho_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('ohho_record_match_apply', sa.Column('another_user_match_condition_id', sa.Integer(), nullable=True))
    op.add_column('ohho_record_match_apply', sa.Column('one_user_match_condition_id', sa.Integer(), nullable=True))
    op.drop_constraint('ohho_record_match_apply_ibfk_3', 'ohho_record_match_apply', type_='foreignkey')
    op.create_foreign_key(None, 'ohho_record_match_apply', 'ohho_record_match_condition', ['another_user_match_condition_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ohho_record_match_apply', 'ohho_record_match_condition', ['one_user_match_condition_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ohho_record_match_apply', 'match_condition_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_record_match_apply', sa.Column('match_condition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ohho_record_match_apply', type_='foreignkey')
    op.drop_constraint(None, 'ohho_record_match_apply', type_='foreignkey')
    op.create_foreign_key('ohho_record_match_apply_ibfk_3', 'ohho_record_match_apply', 'ohho_record_match_condition', ['match_condition_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ohho_record_match_apply', 'one_user_match_condition_id')
    op.drop_column('ohho_record_match_apply', 'another_user_match_condition_id')
    op.drop_constraint(None, 'ohho_record_match_agree', type_='foreignkey')
    op.drop_column('ohho_record_match_agree', 'user_id')
    op.drop_column('ohho_record_friend_apply', 'message')
    # ### end Alembic commands ###
