"""empty message

Revision ID: b86534dfc6b4
Revises: ac4cf40c46fc
Create Date: 2017-11-24 19:00:20.193351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86534dfc6b4'
down_revision = 'ac4cf40c46fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_user_accuracy_extension', sa.Column('certification', sa.SmallInteger(), nullable=True))
    op.drop_constraint('test_phone_distance_ibfk_1', 'test_phone_distance', type_='foreignkey')
    op.drop_constraint('test_phone_distance_ibfk_2', 'test_phone_distance', type_='foreignkey')
    op.create_foreign_key(None, 'test_phone_distance', 'test_phone_position', ['phone_one'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'test_phone_distance', 'test_phone_position', ['phone_another'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_phone_distance', type_='foreignkey')
    op.drop_constraint(None, 'test_phone_distance', type_='foreignkey')
    op.create_foreign_key('test_phone_distance_ibfk_2', 'test_phone_distance', 'test_phone_position', ['phone_another'], ['id'])
    op.create_foreign_key('test_phone_distance_ibfk_1', 'test_phone_distance', 'test_phone_position', ['phone_one'], ['id'])
    op.drop_column('ohho_user_accuracy_extension', 'certification')
    # ### end Alembic commands ###
