"""empty message

Revision ID: cd9a3da6dab2
Revises: 4d977d394190
Create Date: 2017-12-04 15:06:39.058947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd9a3da6dab2'
down_revision = '4d977d394190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_map_information', sa.Column('building', sa.String(length=16), nullable=True))
    op.add_column('ohho_map_information', sa.Column('location_type', sa.Integer(), nullable=True))
    op.drop_column('ohho_map_information', 'building_id')
    op.add_column('ohho_user_accuracy_extension', sa.Column('able2match', sa.Integer(), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('degree_id', sa.Integer(), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('favourite_live_city', sa.String(length=64), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('occupation_id', sa.Integer(), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_interest', ['degree_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_interest', ['occupation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ohho_user_accuracy_extension', 'ohho_interest', ['position_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ohho_user_accuracy_extension', 'current')
    op.drop_column('ohho_user_accuracy_extension', 'source_icon')
    op.drop_column('ohho_user_accuracy_extension', 'weight')
    op.drop_column('ohho_user_accuracy_extension', 'icon')
    op.drop_column('ohho_user_accuracy_extension', 'education')
    op.drop_column('ohho_user_accuracy_extension', 'email')
    op.drop_column('ohho_user_accuracy_extension', 'marriage')
    op.drop_column('ohho_user_accuracy_extension', 'resume')
    op.drop_column('ohho_user_accuracy_extension', 'blood')
    op.drop_column('ohho_user_accuracy_extension', 'interest')
    op.add_column('test_rssi', sa.Column('real_distance', sa.Float(), nullable=True))
    op.add_column('test_rssi_distance', sa.Column('compute_distance', sa.Float(), nullable=True))
    op.add_column('test_rssi_distance', sa.Column('compute_type', sa.SmallInteger(), nullable=True))
    op.add_column('test_rssi_distance', sa.Column('real_distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_rssi_distance', 'real_distance')
    op.drop_column('test_rssi_distance', 'compute_type')
    op.drop_column('test_rssi_distance', 'compute_distance')
    op.drop_column('test_rssi', 'real_distance')
    op.add_column('ohho_user_accuracy_extension', sa.Column('interest', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('blood', mysql.VARCHAR(length=5), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('resume', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('marriage', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('email', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('education', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('icon', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('weight', mysql.FLOAT(), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('source_icon', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('ohho_user_accuracy_extension', sa.Column('current', mysql.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_constraint(None, 'ohho_user_accuracy_extension', type_='foreignkey')
    op.drop_column('ohho_user_accuracy_extension', 'position_id')
    op.drop_column('ohho_user_accuracy_extension', 'occupation_id')
    op.drop_column('ohho_user_accuracy_extension', 'favourite_live_city')
    op.drop_column('ohho_user_accuracy_extension', 'degree_id')
    op.drop_column('ohho_user_accuracy_extension', 'able2match')
    op.add_column('ohho_map_information', sa.Column('building_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('ohho_map_information', 'location_type')
    op.drop_column('ohho_map_information', 'building')
    # ### end Alembic commands ###
