"""empty message

Revision ID: e456eb6c0e3a
Revises: 0f1056ebcdb6
Create Date: 2017-12-21 17:31:38.916305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e456eb6c0e3a'
down_revision = '0f1056ebcdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
