"""empty message

Revision ID: e99422f251dc
Revises: edf65e9e650c
Create Date: 2017-12-11 18:05:17.786611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99422f251dc'
down_revision = 'edf65e9e650c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_complete_meet_feedback', sa.Column('impression', sa.String(length=128), nullable=True))
    op.add_column('ohho_user_impression', sa.Column('apply_id', sa.Integer(), nullable=True))
    op.add_column('ohho_user_impression', sa.Column('type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ohho_user_impression', 'ohho_record_match_apply', ['apply_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ohho_user_impression', type_='foreignkey')
    op.drop_column('ohho_user_impression', 'type')
    op.drop_column('ohho_user_impression', 'apply_id')
    op.drop_column('ohho_complete_meet_feedback', 'impression')
    # ### end Alembic commands ###
