"""empty message

Revision ID: edde95d818d9
Revises: 7480f5424cd6
Create Date: 2017-12-05 15:39:54.774185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edde95d818d9'
down_revision = '7480f5424cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_user_favourite_movie', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('ohho_user_favourite_music', sa.Column('album', sa.String(length=128), nullable=True))
    op.add_column('ohho_user_favourite_music', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('ohho_user_favourite_music', sa.Column('publisher', sa.String(length=128), nullable=True))
    op.add_column('ohho_user_favourite_music', sa.Column('singer', sa.String(length=64), nullable=True))
    op.add_column('ohho_user_favourite_sport', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohho_user_favourite_sport', 'index')
    op.drop_column('ohho_user_favourite_music', 'singer')
    op.drop_column('ohho_user_favourite_music', 'publisher')
    op.drop_column('ohho_user_favourite_music', 'index')
    op.drop_column('ohho_user_favourite_music', 'album')
    op.drop_column('ohho_user_favourite_movie', 'index')
    # ### end Alembic commands ###
