"""empty message

Revision ID: edf65e9e650c
Revises: edde95d818d9
Create Date: 2017-12-08 09:55:14.315564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edf65e9e650c'
down_revision = 'edde95d818d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ohho_match_log')
    op.drop_table('ohho_match_condition')
    op.drop_table('ohho_user_display_configuration')
    op.drop_table('city')
    op.drop_table('province')
    op.drop_table('ohho_match_label')
    op.drop_table('ohho_watchword')
    op.drop_column('ohho_complete_meet_feedback', 'impression')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohho_complete_meet_feedback', sa.Column('impression', mysql.VARCHAR(length=128), nullable=True))
    op.create_table('ohho_watchword',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('changed_at', mysql.DATETIME(), nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('first', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('second', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ohho_match_label',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('changed_at', mysql.DATETIME(), nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ohho_match_label.id'], name='ohho_match_label_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('province',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('administration_id', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('city',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('administration_id', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('province_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ohho_user_display_configuration',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('changed_at', mysql.DATETIME(), nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('distance', mysql.FLOAT(), nullable=True),
    sa.Column('has_sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_identity_card', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_real_name', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_email', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_icon', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_source_icon', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_nickname', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_birthday', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_height', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_marriage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_resume', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_blood', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_hometown', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_current', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_industry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_body_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_smoke_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_drink_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_work_domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_profession_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_school', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_company', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_education', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('has_interest', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ohho_match_condition',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('changed_at', mysql.DATETIME(), nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('big_height', mysql.FLOAT(), nullable=True),
    sa.Column('small_height', mysql.FLOAT(), nullable=True),
    sa.Column('big_weight', mysql.FLOAT(), nullable=True),
    sa.Column('small_weight', mysql.FLOAT(), nullable=True),
    sa.Column('marriage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hometown', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('current', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('industry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('body_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('smoke_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('drink_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('work_domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('profession_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('interest', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['body_type_id'], ['ohho_body_type.id'], name='ohho_match_condition_ibfk_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drink_id'], ['ohho_drink.id'], name='ohho_match_condition_ibfk_5', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_id'], ['ohho_industry.id'], name='ohho_match_condition_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profession_id'], ['ohho_profession.id'], name='ohho_match_condition_ibfk_7', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smoke_id'], ['ohho_smoke.id'], name='ohho_match_condition_ibfk_4', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ohho_user.id'], name='ohho_match_condition_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_domain_id'], ['ohho_work_domain.id'], name='ohho_match_condition_ibfk_6', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ohho_match_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('changed_at', mysql.DATETIME(), nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_one_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_another_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('match_condition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('make_friends', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('meet', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_condition_id'], ['ohho_user.id'], name='ohho_match_log_ibfk_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_another_id'], ['ohho_user.id'], name='ohho_match_log_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_one_id'], ['ohho_user.id'], name='ohho_match_log_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
