PERMISSION_GROUP_USER_RELATION_ADD_URL = "/backstage/management/permission/group/user/relation/add/"
PERMISSION_GROUP_USER_RELATION_DELETE_URL = "/backstage/management/permission/group/user/relation/delete/"
PERMISSION_GROUP_USER_RELATION_HTML = "backstage/management/permission/group_user_relation/group_user_relation.html"
PERMISSION_GROUP_USER_RELATION_DELETE_HTML = "backstage/management/permission/group_user_relation/group_user_relation_delete.html"

PERMISSION_PAGE_BACKSTAGE_ADD_HTML = "backstage/management/permission/page/page_add.html"
PERMISSION_PAGE_BACKSTAGE_LIST_HTML = "backstage/management/permission/page/page_list.html"
PERMISSION_PAGE_BACKSTAGE_DETAIL_HTML = "backstage/management/permission/page/page_detail.html"
PERMISSION_PAGE_BACKSTAGE_DELETE_HTML = "backstage/management/permission/page/page_delete.html"
PERMISSION_PAGE_BACKSTAGE_ADD_URL = "/backstage/management/permission/page/add/"
PERMISSION_PAGE_BACKSTAGE_LIST_URL = "/backstage/management/permission/page/list/"
PERMISSION_PAGE_BACKSTAGE_DETAIL_URL = "/backstage/management/permission/page/detail/"
PERMISSION_PAGE_BACKSTAGE_DELETE_URL = "/backstage/management/permission/page/delete/"

PERMISSION_GROUP_BACKSTAGE_ADD_HTML = "backstage/management/permission/group/group_add.html"
PERMISSION_GROUP_BACKSTAGE_LIST_HTML = "backstage/management/permission/group/group_list.html"
PERMISSION_GROUP_BACKSTAGE_DETAIL_HTML = "backstage/management/permission/group/group_detail.html"
PERMISSION_GROUP_BACKSTAGE_DELETE_HTML = "backstage/management/permission/group/group_delete.html"
PERMISSION_GROUP_BACKSTAGE_ADD_URL = "/backstage/management/permission/group/add/"
PERMISSION_GROUP_BACKSTAGE_LIST_URL = "/backstage/management/permission/group/list/"
PERMISSION_GROUP_BACKSTAGE_DETAIL_URL = "/backstage/management/permission/group/detail/"
PERMISSION_GROUP_BACKSTAGE_DELETE_URL = "/backstage/management/permission/group/delete/"

PERMISSION_GROUP_PAGE_RELATION_BACKSTAGE_ADD_HTML = "backstage/management/permission/group_page_relation/group_page_relation_add.html"
PERMISSION_GROUP_PAGE_RELATION_BACKSTAGE_LIST_HTML = "backstage/management/permission/group_page_relation/group_page_relation_list.html"
PERMISSION_GROUP_PAGE_RELATION_BACKSTAGE_DETAIL_HTML = "backstage/management/permission/group_page_relation/group_page_relation_detail.html"
PERMISSION_GROUP_PAGE_RELATION_BACKSTAGE_DELETE_HTML = "backstage/management/permission/group_page_relation/group_page_relation_delete.html"
PERMISSION_GROUP_PAGE_RELATION_BACKSTAGE_ADD_URL = "/backstage/management/permission/group/permission/add/"
PERMISSION_GROUP_PAGE_RELATION_BACKSTAGE_LIST_URL = "/backstage/management/permission/group/permission/list/"
PERMISSION_GROUP_PAGE_RELATION_BACKSTAGE_DETAIL_URL = "/backstage/management/permission/group/permission/detail/"
PERMISSION_GROUP_PAGE_RELATION_BACKSTAGE_DELETE_URL = "/backstage/management/permission/group/permission/delete/"
