# redis
REDIS_APPLY_TIMESTAMP_NAME = "apply_timestamp"
REDIS_APPLY_TIMESTAMP_KEY = "apply_polling_now"

# user description
DESCRIPTION_TYPE_I_AM = 1
DESCRIPTION_TYPE_I_LIKE = 2
DESCRIPTION_TYPE_I_UNLIKE = 3
DESCRIPTION_TYPE_I_HOPE = 4
