BASE_COUNTRY_CODE_BACKSTAGE_ADD_HTML = "backstage/management/base/country_code/country_code_add.html"
BASE_COUNTRY_CODE_BACKSTAGE_LIST_HTML = "backstage/management/base/country_code/country_code_list.html"
BASE_COUNTRY_CODE_BACKSTAGE_DETAIL_HTML = "backstage/management/base/country_code/country_code_detail.html"
BASE_COUNTRY_CODE_BACKSTAGE_DELETE_HTML = "backstage/management/base/country_code/country_code_delete.html"
BASE_COUNTRY_CODE_BACKSTAGE_ADD_URL = "/backstage/management/base/country_code/add/"
BASE_COUNTRY_CODE_BACKSTAGE_LIST_URL = "/backstage/management/base/country_code/list/"
BASE_COUNTRY_CODE_BACKSTAGE_DETAIL_URL = "/backstage/management/base/country_code/detail/"
BASE_COUNTRY_CODE_BACKSTAGE_DELETE_URL = "/backstage/management/base/country_code/delete/"


BASE_INTEREST_BACKSTAGE_ADD_HTML = "backstage/management/base/interest_backstage/interest_add.html"
BASE_INTEREST_BACKSTAGE_LIST_HTML = "backstage/management/base/interest_backstage/interest_list.html"
BASE_INTEREST_BACKSTAGE_DETAIL_HTML = "backstage/management/base/interest_backstage/interest_detail.html"
BASE_INTEREST_BACKSTAGE_DELETE_HTML = "backstage/management/base/interest_backstage/interest_delete.html"
BASE_INTEREST_BACKSTAGE_ADD_URL = "/backstage/management/base/interest_backstage/add/"
BASE_INTEREST_BACKSTAGE_LIST_URL = "/backstage/management/base/interest_backstage/list/"
BASE_INTEREST_BACKSTAGE_DETAIL_URL = "/backstage/management/base/interest_backstage/detail/"
BASE_INTEREST_BACKSTAGE_DELETE_URL = "/backstage/management/base/interest_backstage/delete/"

BASE_SENSITIVE_BACKSTAGE_ADD_HTML = "backstage/management/base/sensitive/add.html"
BASE_SENSITIVE_BACKSTAGE_LIST_HTML = "backstage/management/base/sensitive/list.html"
BASE_SENSITIVE_BACKSTAGE_DETAIL_HTML = "backstage/management/base/sensitive/detail.html"
BASE_SENSITIVE_BACKSTAGE_DELETE_HTML = "backstage/management/base/sensitive/delete.html"
BASE_SENSITIVE_BACKSTAGE_ADD_URL = "/backstage/management/base/sensitive/add/"
BASE_SENSITIVE_BACKSTAGE_LIST_URL = "/backstage/management/base/sensitive/list/"
BASE_SENSITIVE_BACKSTAGE_DETAIL_URL = "/backstage/management/base/sensitive/detail/"
BASE_SENSITIVE_BACKSTAGE_DELETE_URL = "/backstage/management/base/sensitive/delete/"


BASE_USER_DISPLAY_CONFIG_ADD_HTML = "backstage/management/base/user_display_configuration/user_display_config_add.html"
BASE_USER_DISPLAY_CONFIG_LIST_HTML = "backstage/management/base/user_display_configuration/user_display_config_list.html"
BASE_USER_DISPLAY_CONFIG_DETAIL_HTML = "backstage/management/base/user_display_configuration/user_display_config_detail.html"
BASE_USER_DISPLAY_CONFIG_ADD_URL = "/backstage/management/base/user_display_configuration/add/"
BASE_USER_DISPLAY_CONFIG_LIST_URL = "/backstage/management/base/user_display_configuration/list/"
BASE_USER_DISPLAY_CONFIG_DETAIL_URL = "/backstage/management/base/user_display_configuration/detail/"

BASE_WATCHWORD_ADD_HTML = "backstage/management/base/watchword/watchword_add.html"
BASE_WATCHWORD_LIST_HTML = "backstage/management/base/watchword/watchword_list.html"
BASE_WATCHWORD_DETAIL_HTML = "backstage/management/base/watchword/watchword_detail.html"
BASE_WATCHWORD_ADD_URL = "/backstage/management/base/watchword/add/"
BASE_WATCHWORD_LIST_URL = "/backstage/management/base/watchword/list/"
BASE_WATCHWORD_DETAIL_URL = "/backstage/management/base/watchword/detail/"

BASE_DRINK_ADD_HTML = "backstage/management/base/drink/drink_add.html"
BASE_DRINK_LIST_HTML = "backstage/management/base/drink/drink_list.html"
BASE_DRINK_DETAIL_HTML = "backstage/management/base/drink/drink_detail.html"
BASE_DRINK_ADD_URL = "/backstage/management/base/drink/add/"
BASE_DRINK_LIST_URL = "/backstage/management/base/drink/list/"
BASE_DRINK_DETAIL_URL = "/backstage/management/base/drink/detail/"

BASE_SMOKE_ADD_HTML = "backstage/management/base/smoke/smoke_add.html"
BASE_SMOKE_LIST_HTML = "backstage/management/base/smoke/smoke_list.html"
BASE_SMOKE_DETAIL_HTML = "backstage/management/base/smoke/smoke_detail.html"
BASE_SMOKE_ADD_URL = "/backstage/management/base/smoke/add/"
BASE_SMOKE_LIST_URL = "/backstage/management/base/smoke/list/"
BASE_SMOKE_DETAIL_URL = "/backstage/management/base/smoke/detail/"

BASE_PROFESSION_ADD_HTML = "backstage/management/base/profession/profession_add.html"
BASE_PROFESSION_LIST_HTML = "backstage/management/base/profession/profession_list.html"
BASE_PROFESSION_DETAIL_HTML = "backstage/management/base/profession/profession_detail.html"
BASE_PROFESSION_ADD_URL = "/backstage/management/base/profession/add/"
BASE_PROFESSION_LIST_URL = "/backstage/management/base/profession/list/"
BASE_PROFESSION_DETAIL_URL = "/backstage/management/base/profession/detail/"

BASE_INDUSTRY_ADD_HTML = "backstage/management/base/industry/industry_add.html"
BASE_INDUSTRY_LIST_HTML = "backstage/management/base/industry/industry_list.html"
BASE_INDUSTRY_DETAIL_HTML = "backstage/management/base/industry/industry_detail.html"
BASE_INDUSTRY_ADD_URL = "/backstage/management/base/industry/add/"
BASE_INDUSTRY_LIST_URL = "/backstage/management/base/industry/list/"
BASE_INDUSTRY_DETAIL_URL = "/backstage/management/base/industry/detail/"

BASE_BODY_TYPE_ADD_HTML = "backstage/management/base/body_type/body_type_add.html"
BASE_BODY_TYPE_LIST_HTML = "backstage/management/base/body_type/body_type_list.html"
BASE_BODY_TYPE_DETAIL_HTML = "backstage/management/base/body_type/body_type_detail.html"
BASE_BODY_TYPE_ADD_URL = "/backstage/management/base/body_type/add/"
BASE_BODY_TYPE_LIST_URL = "/backstage/management/base/body_type/list/"
BASE_BODY_TYPE_DETAIL_URL = "/backstage/management/base/body_type/detail/"

BASE_WORK_DOMAIN_ADD_HTML = "backstage/management/base/work_domain/work_domain_add.html"
BASE_WORK_DOMAIN_LIST_HTML = "backstage/management/base/work_domain/work_domain_list.html"
BASE_WORK_DOMAIN_DETAIL_HTML = "backstage/management/base/work_domain/work_domain_detail.html"
BASE_WORK_DOMAIN_ADD_URL = "/backstage/management/base/work_domain/add/"
BASE_WORK_DOMAIN_LIST_URL = "/backstage/management/base/work_domain/list/"
BASE_WORK_DOMAIN_DETAIL_URL = "/backstage/management/base/work_domain/detail/"

BASE_MATCH_CONDITION_ADD_HTML = "backstage/management/base/match_condition/match_condition_add.html"
BASE_MATCH_CONDITION_LIST_HTML = "backstage/management/base/match_condition/match_condition_list.html"
BASE_MATCH_CONDITION_DETAIL_HTML = "backstage/management/base/match_condition/match_condition_detail.html"
BASE_MATCH_CONDITION_ADD_URL = "/backstage/management/base/match/condition/add/"
BASE_MATCH_CONDITION_LIST_URL = "/backstage/management/base/match/condition/list/"
BASE_MATCH_CONDITION_DETAIL_URL = "/backstage/management/base/match/condition/detail/"

BASE_MATCH_LABEL_ADD_HTML = "backstage/management/base/match_label/match_label_add.html"
BASE_MATCH_LABEL_LIST_HTML = "backstage/management/base/match_label/match_label_list.html"
BASE_MATCH_LABEL_DETAIL_HTML = "backstage/management/base/match_label/match_label_detail.html"
BASE_MATCH_LABEL_ADD_URL = "/backstage/management/base/match/label/add/"
BASE_MATCH_LABEL_LIST_URL = "/backstage/management/base/match/label/list/"
BASE_MATCH_LABEL_DETAIL_URL = "/backstage/management/base/match/label/detail/"
