HOME_URL = "/rest/api/ohho/test/home/app/quick/find/"
HOME_URL_OLD = "/rest/api/ohho/test/home/app/"

# HOME
HOME_HTML = "test/home/home.html"
HOME_APP_HTML = "test/home/home_app.html"
HOME_APP_INTERFACES_HTML = "test/home/home_app_interfaces.html"
HOME_APP_QUICK_FIND_HTML = "test/home/home_app_quick_find.html"
HOME_BACKSTAGE_HTML = "test/home/home_backstage.html"
HOME_BACKSTAGE_INTERFACES_HTML = "test/home/home_backstage_interfaces.html"
HOME_TEST_HTML = "test/home/home_test.html"
INTERFACES_HTML = "test/home/interfaces.html"

# MEET
GET_MEET_TOPIC_URL = "/rest/api/ohho/get/meet/topic/"
ADD_MEET_URL = "/rest/api/ohho/add/meet/"
AGREE_MEET_URL = "/rest/api/ohho/agree/meet/"
APPLY_MEET_URL = "/rest/api/ohho/apply/meet/"
CANCEL_MEET_URL = "/rest/api/ohho/cancel/meet/"
MEET_URL = "/rest/api/ohho/meet/"
GET_MEET_STATE_URL = "/rest/api/ohho/get/meet/state/"
MET_BY_DEVICE_URL = "/rest/api/ohho/met/by/device/"
MET_BY_HAND_URL = "/rest/api/ohho/met/by/hand/"
END_MEET_URL = "/rest/api/ohho/end/meet/"
REFUSE_MEET_URL = "/rest/api/ohho/refuse/meet/"

GET_MEET_TOPIC_HTML = "test/meet/get_meet_topic.html"
ADD_MEET_HTML = "test/meet/add_meet.html"
AGREE_MEET_HTML = "test/meet/agree_meet.html"
APPLY_MEET_HTML = "test/meet/apply_meet.html"
CANCEL_MEET_HTML = "test/meet/cancel_meet.html"
MEET_HTML = "test/meet/meet.html"
GET_MEET_STATE_HTML = "test/meet/get_meet_state.html"
MET_BY_DEVICE_HTML = "test/meet/meet_by_device.html"
MET_BY_HAND_HTML = "test/meet/meet_by_hand.html"
END_MEET_HTML = "test/meet/meet_end.html"
REFUSE_MEET_HTML = "test/meet/refuse_meet.html"

# MATCH
MATCH_URL = "/rest/api/ohho/match/"
VERSION2_MATCH_URL = "/rest/api/ohho/version2/match/"
ADD_EXCLUDE_URL = "/rest/api/ohho/add/exclude/"
ADD_MATCH_CONDITION_URL = "/rest/api/ohho/add/match/condition/"
CLOSE_MATCH_SWITCH_URL = "/rest/api/ohho/close/match/switch/"
OPEN_MATCH_SWITCH_URL = "/rest/api/ohho/open/match/switch/"
SET_MATCH_SWITCH_URL = "/rest/api/ohho/set/match/switch/"
GET_MATCH_CONDITION_URL = "/rest/api/ohho/get/match/condition/"
POLLING_GET_APPLY_URL = "/rest/api/ohho/polling/get/apply/apply/"
POLLING_GET_APPLIED_URL = "/rest/api/ohho/polling/get/apply/state/"

MATCH_HTML = "test/match/match.html"
VERSION2_MATCH_HTML = "test/match/version2_match.html"
ADD_EXCLUDE_HTML = "test/match/add_exclude.html"
ADD_MATCH_CONDITION_HTML = "test/match/add_match_condition.html"
CLOSE_MATCH_SWITCH_HTML = "test/match/close_match_switch.html"
OPEN_MATCH_SWITCH_HTML = "test/match/open_match_switch.html"
SET_MATCH_SWITCH_HTML = "test/match/set_match_switch.html"
GET_MATCH_CONDITION_HTML = "test/match/get_match_condition.html"
POLLING_GET_APPLY_HTML = "test/match/polling_get_apply_apply.html"
POLLING_GET_APPLIED_HTML = "test/match/polling_get_apply_state.html"

# FRIEND
IM_ADD_BLACK_URL = "/rest/api/ohho/im/add/black/"
AGREE_FRIEND_URL = "/rest/api/ohho/agree/friend/"
APPLY_FRIEND_URL = "/rest/api/ohho/apply/friend/"
CLOSE_ONLINE_SWITCH_URL = "/rest/api/ohho/close/online/switch/"
OPEN_ONLINE_SWITCH_URL = "/rest/api/ohho/open/online/switch/"
SET_ONLINE_SWITCH_URL = "/rest/api/ohho/set/online/switch/"
LIST_APPLY_FRIEND_URL = "/rest/api/ohho/list/apply/friend/"
LIST_BLACKS_URL = "/rest/api/ohho/im/list/blacks/"
LIST_FRIENDS_URL = "/rest/api/ohho/im/list/friends/"
REFUSE_FRIEND_URL = "/rest/api/ohho/refuse/friend/"
REMOVE_BLACK_URL = "/rest/api/ohho/im/remove/black/"
REMOVE_FRIEND_URL = "/rest/api/ohho/remove/friend/"

IM_ADD_BLACK_HTML = "test/friend/add_black.html"
AGREE_FRIEND_HTML = "test/friend/agree_friend.html"
APPLY_FRIEND_HTML = "test/friend/apply_friend.html"
CLOSE_ONLINE_SWITCH_HTML = "test/friend/close_online_switch.html"
OPEN_ONLINE_SWITCH_HTML = "test/friend/open_online_switch.html"
SET_ONLINE_SWITCH_HTML = "test/friend/set_online_switch.html"
LIST_APPLY_FRIEND_HTML = "test/friend/list_apply_friend.html"
LIST_BLACKS_HTML = "test/friend/list_blacks.html"
LIST_FRIENDS_HTML = "test/friend/list_friends.html"
REFUSE_FRIEND_HTML = "test/friend/refuse_friend.html"
REMOVE_BLACK_HTML = "test/friend/remove_black.html"
REMOVE_FRIEND_HTML = "test/friend/remove_friend.html"

# BASIC DATA
GET_BASIC_DATA_URL = "/rest/api/ohho/get/basic/data/"
ADD_BODY_TYPE_URL = "/rest/api/ohho/add/body/type/"
ADD_DRINK_URL = "/rest/api/ohho/add/drink/"
ADD_INDUSTRY_URL = "/rest/api/ohho/add/industry/"
ADD_PROFESSION_URL = "/rest/api/ohho/add/profession/"
ADD_SMOKE_URL = "/rest/api/ohho/add/smoke/"
ADD_WORK_DOMAIN_URL = "/rest/api/ohho/add/work/domain/"

GET_BASIC_DATA_HTML = "test/base/get_basic_data.html"
ADD_BODY_TYPE_HTML = "test/base/add_body_type.html"
ADD_DRINK_HTML = "test/base/add_drink.html"
ADD_INDUSTRY_HTML = "test/base/add_industry.html"
ADD_PROFESSION_HTML = "test/base/add_profession.html"
ADD_SMOKE_HTML = "test/base/add_smoke.html"
ADD_WORK_DOMAIN_HTML = "test/base/add_work_domain.html"

# REPORT
ADD_REPORT_URL = "/rest/api/ohho/add/report/"
ADD_REPORT_HTML = "test/report/add_report.html"

# DEVICE
ADD_DEVICE_URL = "/rest/api/ohho/add/device/"
ADD_DEVICE_SETTING_URL = "/rest/api/ohho/add/device/setting/"
BIND_DEVICE_URL = "/rest/api/ohho/bind/device/"
BLUE_TOOTH_POSITION_URL = "/rest/api/ohho/bluetooth/position/"
CANCEL_LOST_URL = "/rest/api/ohho/cancel/lost/"
CELLPHONE_UNBIND_DEVICE_URL = "/rest/api/ohho/cellphone/unbind/device/"
FIND_DEVICE_POSITION_URL = "/rest/api/ohho/find/device/position/"
GET_BOUND_DEVICES_URL = "/rest/api/ohho/get/bound/devices/"
GET_DEVICE_SETTING_URL = "/rest/api/ohho/get/device/setting/"
GET_DEVICE_VERSION_URL = "/rest/api/ohho/get/device/version/"
GET_USER_AND_DEVICE_IMEI_URL = "/rest/api/ohho/get/user/and/device/imei/"
IS_DEVICE_VALID_URL = "/rest/api/ohho/is/device/valid/"
SET_DEVICE_USE_URL = "/rest/api/ohho/set/device/use/"
SET_LOST_URL = "/rest/api/ohho/set/lost/"
UNBIND_DEVICE_URL = "/rest/api/ohho/unbind/device/"
UPDATE_DEVICE_SETTING_URL = "/rest/api/ohho/update/device/setting/"

ADD_DEVICE_HTML = "test/device/add_device.html"
ADD_DEVICE_SETTING_HTML = "test/device/add_device_setting.html"
BIND_DEVICE_HTML = "test/device/bind_device.html"
BLUE_TOOTH_POSITION_HTML = "test/device/bluetooth_position.html"
CANCEL_LOST_HTML = "test/device/cancel_lost.html"
CELLPHONE_UNBIND_DEVICE_HTML = "test/device/cellphone_unbind_device.html"
FIND_DEVICE_POSITION_HTML = "test/device/find_device_position.html"
GET_BOUND_DEVICES_HTML = "test/device/get_bound_devices.html"
GET_DEVICE_SETTING_HTML = "test/device/get_device_setting.html"
GET_DEVICE_VERSION_HTML = "test/device/get_device_version.html"
GET_USER_AND_DEVICE_IMEI_HTML = "test/device/get_user_and_device_imei.html"
IS_DEVICE_VALID_HTML = "test/device/is_device_valid.html"
SET_DEVICE_USE_HTML = "test/device/set_device_use.html"
SET_LOST_HTML = "test/device/set_lost.html"
UNBIND_DEVICE_HTML = "test/device/unbind_device.html"
UPDATE_DEVICE_SETTING_HTML = "test/device/update_device_setting.html"

# FEEDBACK
ADD_FEEDBACK_URL = "/rest/api/ohho/add/feedback/"
ADD_CANCEL_MEET_FEEDBACK_URL = "/rest/api/ohho/add/cancel/meet/feedback/"
ADD_COMPLETE_MEET_FEEDBACK_URL = "/rest/api/ohho/add/complete/meet/feedback/"

ADD_FEEDBACK_HTML = "test/feedback/add_feedback.html"
ADD_CANCEL_MEET_FEEDBACK_HTML = "test/feedback/add_cancel_meet_feedback.html"
ADD_COMPLETE_MEET_FEEDBACK_HTML = "test/feedback/add_complete_meet_feedback.html"

# USER
ADD_USER_EXTENSION_URL = "/rest/api/ohho/add/user/accuracy/extension/"
ADD_USER_ICON_URL = "/rest/api/ohho/add/user/icon/"
ADD_USER_EXCLUDE_URL = "/rest/api/ohho/add/user/exclude/"
REBIND_CELLPHONE_URL = "/rest/api/ohho/rebind/cellphone/"
GET_USER_BY_DEVICE_URL = "/rest/api/ohho/get/user/by/device/"
GET_USER_INFORMATION_URL = "/rest/api/ohho/get/user/information/"
GET_USER_PERSONAL_INFORMATION_URL = "/rest/api/ohho/get/user/personal/information/"
GET_USER_PERSONAL_PAGE_URL = "/rest/api/ohho/get/user/personal/page/"
UPDATE_CELLPHONE_NUMBER_URL = "/rest/api/ohho/update/cellphone/number/"

ADD_USER_EXTENSION_HTML = "test/user/add_user_accuracy_extension.html"
ADD_USER_ICON_HTML = "test/user/add_user_icon.html"
ADD_USER_EXCLUDE_HTML = "test/user/add_user_exclude.html"
REBIND_CELLPHONE_HTML = "test/user/rebind_cellphone.html"
GET_USER_BY_DEVICE_HTML = "test/user/get_user_by_device.html"
GET_USER_INFORMATION_HTML = "test/user/get_user_information.html"
GET_USER_PERSONAL_INFORMATION_HTML = "test/user/get_user_personal_information.html"
GET_USER_PERSONAL__HTML = "test/user/get_user_personal_page.html"
UPDATE_CELLPHONE_NUMBER_HTML = "test/user/update_cellphone_number.html"

# CODE
CHECK_VERIFICATION_CODE_URL = "/rest/api/ohho/check/verification/code/"
SEND_VERIFICATION_CODE_URL = "/rest/api/ohho/send/verification/code/"

CHECK_VERIFICATION_CODE_HTML = "test/code/check_verification_code.html"
SEND_VERIFICATION_CODE_HTML = "test/code/send_verification_code.html"

# MAP
GET_FRIEND_MAP_POSITION_URL = "/rest/api/ohho/get/friend/map/position/"
GET_MAP_POSITIONS_URL = "/rest/api/ohho/get/map/positions/"

UPLOAD_MAP_POSITION_URL = "/rest/api/ohho/upload/map/position/"

GET_FRIEND_MAP_POSITION_HTML = "test/map/get_friend_map_position.html"
GET_MAP_POSITIONS_HTML = "test/map/get_map_positions.html"
UPLOAD_MAP_POSITION_HTML = "test/map/upload_map_position.html"


# REGISTER AND LOGIN
LOGIN_URL = "/rest/api/ohho/login/"
LOGIN_BY_CODE_URL = "/rest/api/ohho/login/by/code/"
LOGOUT_URL = "/rest/api/ohho/logout/"
REGISTER_URL = "/rest/api/ohho/register/"
RESET_PASSWORD_URL = "/rest/api/ohho/reset/password/"

LOGIN_HTML = "test/register/login.html"
LOGIN_BY_CODE_HTML = "test/register/login_by_code.html"
LOGOUT_HTML = "test/register/logout.html"
REGISTER_HTML = "test/register/register.html"
RESET_PASSWORD_HTML = "test/register/reset_password.html"

# 提交用户信息
COMPLETE_USER_HTML = "test/user/complete_user.html"
COMPLETE_USER_URL = "/rest/api/ohho/complete/user/"

#压力测试添加用户
STRESS_TESTING_ADD_USER_HTML = "test/stressTesting/add_user.html"
STRESS_TESTING_ADD_USER_URL = "/rest/api/view/ohho/stress/testint/add/user/"
